/**
 * DonkeyCode — MV3 service worker: script sync, injection, sessions, alarms.
 */

const LOG_PREFIX = "[DonkeyCode:background]";

const DEFAULT_SCRIPT_SOURCE_URL =
  "https://api.github.com/repos/MikeBane57/Wolf2.0/contents/?ref=main";

/**
 * Optional baked GitHub defaults: generated by `npm run build` → DonkeyCode/baked-config.js
 * (gitignored). If missing, empty defaults below apply.
 */
try {
  importScripts("baked-config.js");
} catch (e) {
  self.BAKED_GITHUB_DEFAULTS = {
    token: "",
    owner: "",
    repo: "",
    branch: "main",
    path: "sessions/donkeycode-sessions.json",
  };
}

const SESSION_JSON_FILENAME = "donkeycode-sessions.json";

function joinGithubRepoPath(rootDir, ...segments) {
  const parts = [];
  const r = (rootDir || "").trim().replace(/^\/+|\/+$/g, "").replace(/\\/g, "/");
  if (r) parts.push(r);
  for (const seg of segments) {
    const s = (seg || "").trim().replace(/^\/+|\/+$/g, "").replace(/\\/g, "/");
    if (s) parts.push(s);
  }
  return parts.join("/");
}

function defaultSessionFilePathForRoot(sessionsRoot) {
  return joinGithubRepoPath(sessionsRoot, SESSION_JSON_FILENAME);
}

/** User may enter a directory (e.g. sessions) or legacy path ending in .json */
function normalizeUserSessionsRootInput(input) {
  const t = (input || "").trim().replace(/^\/+/, "").replace(/\/+$/g, "");
  if (!t) return "sessions";
  if (/\.json$/i.test(t)) {
    const i = t.lastIndexOf("/");
    return i === -1 ? "" : t.slice(0, i);
  }
  return t;
}

function deriveSessionsRootFromLegacyPath(raw) {
  const path = (raw || "").trim().replace(/^\/+/, "");
  if (!path) return "sessions";
  if (/\.json$/i.test(path)) {
    const i = path.lastIndexOf("/");
    return i === -1 ? "" : path.slice(0, i);
  }
  return path.replace(/\/+$/, "");
}

const STORAGE = {
  SCRIPT_SOURCE: "donkeycode_script_source_url",
  EXTRA_URLS: "donkeycode_extra_script_urls",
  SCRIPTS: "donkeycode_scripts",
  SESSIONS: "donkeycode_sessions",
  SESSION_FOLDERS_V2: "donkeycode_session_folders_v2",
  CURRENT_SESSION_FOLDER: "donkeycode_current_session_folder",
  /** Legacy: flat sessions in sync before folder model */
  SESSIONS_LEGACY_MIGRATED: "donkeycode_sessions_legacy_migrated",
  /** v3: session blobs moved from sync (8KB/item limit) to chrome.storage.local */
  SESSION_STORAGE_MIGRATED: "donkeycode_sessions_storage_migrated_v3",
  LAST_FETCH: "donkeycode_last_script_fetch_ms",
  PENDING_RESTORE: "donkeycode_pending_restore_session",
  SETUP_DISMISSED: "donkeycode_setup_banner_dismissed",
  PENDING_FIRST_POPUP_REFRESH: "donkeycode_pending_first_popup_refresh",
  GITHUB_PAT: "donkeycode_github_pat",
  GITHUB_OWNER: "donkeycode_github_owner",
  GITHUB_REPO: "donkeycode_github_repo",
  GITHUB_BRANCH: "donkeycode_github_branch",
  GITHUB_PATH: "donkeycode_github_path",
  GITHUB_SESSIONS_ROOT: "donkeycode_github_sessions_root",
  GITHUB_SYNC_LAST_ERROR: "donkeycode_github_sync_last_error",
  GITHUB_SYNC_LAST_OK: "donkeycode_github_sync_last_ok",
  /** Set on first install; cleared after popup runs one GitHub session pull when configured */
  PENDING_INITIAL_SESSION_PULL: "donkeycode_pending_initial_session_pull",
};

/** Default URLs opened before restoring a session (user signs in, then continues). */
const LOGIN_WINDOW_URLS = [
  "https://opssuitemain.swacorp.com/",
  "https://www.swalife.com/",
];

const ALARM_DAILY = "donkeycode_daily_script_refresh";

/** Optional broad host patterns (must match manifest optional_host_permissions). */
const OPTIONAL_ORIGIN_PATTERNS = ["http://*/*", "https://*/*"];

const BRIDGE_CS_ID = "donkeycode-bridge";

/** @type {Map<number, Set<string>>} */
const tabInjectedScripts = new Map();

async function hasOriginAccessForUrl(pageUrl) {
  try {
    const u = new URL(pageUrl);
    if (u.protocol !== "http:" && u.protocol !== "https:") return false;
    return await hasOptionalHostAccess();
  } catch (e) {
    return false;
  }
}

async function hasOptionalHostAccess() {
  return chrome.permissions.contains({ origins: OPTIONAL_ORIGIN_PATTERNS });
}

async function registerBridgeContentScripts() {
  try {
    await chrome.scripting.unregisterContentScripts({ ids: [BRIDGE_CS_ID] });
  } catch (e) {
    /* ignore */
  }
  await chrome.scripting.registerContentScripts([
    {
      id: BRIDGE_CS_ID,
      matches: ["http://*/*", "https://*/*"],
      js: ["bridge.js"],
      runAt: "document_start",
      allFrames: false,
    },
  ]);
  log("registered bridge content script");
}

async function unregisterBridgeContentScripts() {
  try {
    await chrome.scripting.unregisterContentScripts({ ids: [BRIDGE_CS_ID] });
    log("unregistered bridge content script");
  } catch (e) {
    /* ignore */
  }
}

async function ensureHostAccessAndBridge() {
  const ok = await hasOptionalHostAccess();
  if (!ok) {
    log("optional http(s) host access not granted — grant in extension settings to run scripts");
    await unregisterBridgeContentScripts();
    return false;
  }
  try {
    await registerBridgeContentScripts();
  } catch (e) {
    logError("registerBridgeContentScripts failed", e);
  }
  return true;
}

if (chrome.permissions && chrome.permissions.onRemoved) {
  chrome.permissions.onRemoved.addListener((details) => {
    if (details.origins && details.origins.length) {
      hasOptionalHostAccess().then((still) => {
        if (!still) unregisterBridgeContentScripts();
        updateInstallBadge().catch(() => {});
      });
    }
  });
}

async function updateInstallBadge() {
  try {
    const dismissed = await chrome.storage.local.get(STORAGE.SETUP_DISMISSED);
    if (dismissed[STORAGE.SETUP_DISMISSED]) {
      await chrome.action.setBadgeText({ text: "" });
      return;
    }
    const hasHost = await hasOptionalHostAccess();
    const scripts = await getStoredScripts();
    const needsPerm = !hasHost;
    const needsScripts = scripts.length === 0;
    if (needsPerm || needsScripts) {
      await chrome.action.setBadgeText({ text: "!" });
      await chrome.action.setBadgeBackgroundColor({ color: needsPerm ? "#C62828" : "#F57C00" });
    } else {
      await chrome.action.setBadgeText({ text: "" });
    }
  } catch (e) {
    logWarn("updateInstallBadge", e);
  }
}

function log(...args) {
  console.log(LOG_PREFIX, ...args);
}

function logWarn(...args) {
  console.warn(LOG_PREFIX, ...args);
}

function logError(...args) {
  console.error(LOG_PREFIX, ...args);
}

/**
 * One-time: derive sessions root from stored GITHUB_PATH and/or baked path.
 */
async function migrateGithubSessionsRootIfNeeded() {
  const d = await chrome.storage.local.get([
    STORAGE.GITHUB_SESSIONS_ROOT,
    STORAGE.GITHUB_PATH,
  ]);
  if (
    Object.prototype.hasOwnProperty.call(d, STORAGE.GITHUB_SESSIONS_ROOT) &&
    d[STORAGE.GITHUB_SESSIONS_ROOT] !== undefined &&
    d[STORAGE.GITHUB_SESSIONS_ROOT] !== null
  ) {
    return;
  }
  const baked = self.BAKED_GITHUB_DEFAULTS || {};
  const rawFromStorage = (d[STORAGE.GITHUB_PATH] || "").trim();
  const rawFromBaked = String(baked.path || "").trim();
  const raw = rawFromStorage || rawFromBaked;
  const root = deriveSessionsRootFromLegacyPath(raw);
  await chrome.storage.local.set({ [STORAGE.GITHUB_SESSIONS_ROOT]: root });
  log("GitHub sessions root migrated:", root, "from", raw || "(default)");
}

function scriptIdFromUrl(url) {
  let h = 2166136261;
  for (let i = 0; i < url.length; i++) {
    h ^= url.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return "dc_" + (h >>> 0).toString(16);
}

/**
 * Parse ==UserScript== metadata and body.
 * @param {string} fullText
 */
function parseUserScript(fullText) {
  const blockMatch = fullText.match(
    /\/\/\s*==UserScript==([\s\S]*?)\/\/\s*==\/UserScript==/i
  );
  const metaText = blockMatch ? blockMatch[1] : "";
  const body = blockMatch
    ? fullText.slice(blockMatch.index + blockMatch[0].length).replace(/^\s*/, "")
    : fullText;

  const matches = [];
  const excludes = [];
  const grants = [];
  const connects = [];
  let userScriptName = "";
  const lines = metaText.split(/\r?\n/);
  for (const line of lines) {
    const m = line.match(/^\s*\/\/\s*@(\S+)\s+(.*)$/);
    if (!m) continue;
    const key = m[1].toLowerCase();
    const val = (m[2] || "").trim();
    if (key === "match") matches.push(val);
    else if (key === "exclude") excludes.push(val);
    else if (key === "grant") grants.push(val);
    else if (key === "connect") connects.push(val);
    else if (key === "name" && val) userScriptName = val;
  }

  if (matches.length === 0) matches.push("*://*/*");

  return { matches, excludes, grants, connects, userScriptName, body };
}

/**
 * @param {string} hostname
 * @param {string} pattern e.g. example.com or *.example.com
 */
function hostMatchesConnect(hostname, pattern) {
  const p = (pattern || "").trim().toLowerCase();
  const h = (hostname || "").toLowerCase();
  if (!p) return false;
  if (p.startsWith("*.")) {
    const suf = p.slice(2);
    return h === suf || h.endsWith("." + suf);
  }
  return h === p;
}

function urlAllowedByConnects(pageUrl, connects) {
  if (!connects || connects.length === 0) return true;
  if (connects.some((c) => String(c).trim() === "*")) return true;
  let u;
  try {
    u = new URL(pageUrl);
  } catch (e) {
    return false;
  }
  if (u.protocol !== "http:" && u.protocol !== "https:") return false;
  for (const c of connects) {
    if (hostMatchesConnect(u.hostname, c.trim())) return true;
  }
  return false;
}

/**
 * Tampermonkey-style @match against a page URL (simplified).
 * @param {string} pattern e.g. *://*.example.com/foo*
 * @param {string} pageUrl
 */
function urlMatchesPattern(pattern, pageUrl) {
  try {
    const u = new URL(pageUrl);
    if (u.protocol === "chrome-extension:" || u.protocol === "chrome:") return false;

    const normalized = pattern.trim();
    const parts = normalized.match(/^(\*|https?|file|ftp):\/\/([^/]+)(\/.*)$/i);
    if (!parts) return false;

    const schemePat = parts[1].toLowerCase();
    const hostPat = parts[2];
    const pathPat = parts[3] || "/";

    const scheme = (u.protocol || "").replace(":", "").toLowerCase();
    if (schemePat !== "*" && schemePat !== scheme) return false;

    if (!hostMatches(hostPat, u.hostname)) return false;
    if (!pathMatches(pathPat, u.pathname + u.search)) return false;
    return true;
  } catch (e) {
    logWarn("match parse error", pattern, e);
    return false;
  }
}

function hostMatches(pat, host) {
  if (pat === "*") return true;
  if (pat.startsWith("*.")) {
    const rest = pat.slice(2);
    return host === rest || host.endsWith("." + rest);
  }
  if (pat.includes("*")) {
    const re = new RegExp(
      "^" +
        pat.replace(/[.+?^${}()|[\]\\]/g, "\\$&").replace(/\*/g, ".*") +
        "$",
      "i"
    );
    return re.test(host);
  }
  return host.toLowerCase() === pat.toLowerCase();
}

function pathMatches(pat, pathAndQuery) {
  const re = new RegExp(
    "^" + pat.replace(/[.+?^${}()|[\]\\]/g, "\\$&").replace(/\*/g, ".*") + "$",
    "i"
  );
  return re.test(pathAndQuery);
}

function scriptMatchesUrl(script, pageUrl) {
  for (const ex of script.excludes || []) {
    if (urlMatchesPattern(ex, pageUrl)) {
      log("URL skipped (exclude)", { id: script.id, pageUrl, ex });
      return false;
    }
  }
  for (const m of script.matches || []) {
    if (urlMatchesPattern(m, pageUrl)) {
      log("URL matched", { id: script.id, pageUrl, match: m });
      return true;
    }
  }
  log("URL skipped (no @match)", { id: script.id, pageUrl });
  return false;
}

/**
 * Injected into MAIN world — runs user code and registers cleanup.
 * Passes Tampermonkey-style GM_xmlhttpRequest when @grant requests it (via
 * new Function argument so each script keeps the correct script id for @connect).
 * Must be self-contained (serialized).
 * @param {{ id: string, code: string, grants?: string[], connects?: string[] }} payload
 */
function donkeycodeInjectMain(payload) {
  const scriptId = payload.id;
  const code = payload.code;
  const grants = payload.grants || [];
  const connects = payload.connects || [];

  const g = typeof window !== "undefined" ? window : globalThis;
  const key = "__donkeycodeCleanups";
  if (!g[key]) g[key] = Object.create(null);
  const cleanups = g[key];
  if (cleanups[scriptId]) {
    try {
      console.log("[DonkeyCode:page] cleaning up before re-inject", scriptId);
      cleanups[scriptId]();
    } catch (e) {
      console.warn("[DonkeyCode:page] cleanup error before inject", scriptId, e);
    }
    delete cleanups[scriptId];
  }

  function ensureGmBridge() {
    if (g.__donkeycodeGmBridge) return;
    g.__donkeycodeGmBridge = true;
    g.__donkeycodeGmPending = Object.create(null);
    g.__donkeycodeGmNextId = 0;
    g.addEventListener("message", function (ev) {
      if (ev.source !== g) return;
      const d = ev.data;
      if (!d || d.type !== "DONKEYCODE_GM_XHR_RESPONSE") return;
      const rec = g.__donkeycodeGmPending[d.id];
      delete g.__donkeycodeGmPending[d.id];
      if (!rec) return;
      const details = rec.details;
      if (d.error) {
        console.warn("[DonkeyCode:page] GM_xmlhttpRequest error", d.error);
        if (details.onerror) details.onerror({ status: 0, statusText: d.error });
      } else if (details.onload) {
        details.onload({
          responseText: d.responseText || "",
          status: d.status || 0,
          statusText: d.statusText || "",
          finalUrl: d.finalUrl || "",
        });
      }
    });
  }

  function makeGmXmlHttpRequest(sid) {
    ensureGmBridge();
    return function (details) {
      const id = ++g.__donkeycodeGmNextId;
      g.__donkeycodeGmPending[id] = { details: details };
      g.postMessage(
        {
          type: "DONKEYCODE_GM_XHR",
          id: id,
          scriptId: sid,
          details: {
            method: (details && details.method) || "GET",
            url: details && details.url,
            headers: details && details.headers,
          },
        },
        "*"
      );
    };
  }

  /** Normalize @grant tokens: "GM_xmlhttpRequest" / "GM.xmlhttpRequest" → "xmlhttprequest" */
  function canonicalGrant(g) {
    let t = String(g).trim().toLowerCase().replace(/\s+/g, "");
    t = t.replace(/\./g, "_");
    if (t.startsWith("gm_")) t = t.slice(3);
    return t;
  }

  const grantSet = {};
  for (let gi = 0; gi < grants.length; gi++) {
    grantSet[canonicalGrant(grants[gi])] = true;
  }

  const wantsGmByMeta = grantSet["xmlhttprequest"];
  const wantsGmByCode = /\bGM_xmlhttpRequest\b/.test(code);
  const wantsGmXhr = wantsGmByMeta || wantsGmByCode;

  /** Pass GM as a Function arg so nested/async code closes over it. Pages using SES
   * lockdown (e.g. lockdown-install.js) strip globals we add to window — lexical
   * binding survives. */
  let gmImpl;
  if (wantsGmXhr) {
    gmImpl = makeGmXmlHttpRequest(scriptId);
    console.log(
      "[DonkeyCode:page] GM_xmlhttpRequest via closure (SES-safe)",
      scriptId,
      { wantsGmByMeta, wantsGmByCode, connects }
    );
  }

  try {
    console.log(
      "[DonkeyCode:page] executing script",
      scriptId,
      wantsGmXhr ? "+GM_xmlhttpRequest" : ""
    );
    const run = wantsGmXhr
      ? new Function("GM_xmlhttpRequest", code)
      : new Function(code);
    if (wantsGmXhr) run(gmImpl);
    else run();
    if (typeof g.__myScriptCleanup === "function") {
      cleanups[scriptId] = g.__myScriptCleanup;
      try {
        delete g.__myScriptCleanup;
      } catch (e) {
        g.__myScriptCleanup = undefined;
      }
      console.log("[DonkeyCode:page] registered __myScriptCleanup", scriptId);
    } else {
      console.log(
        "[DonkeyCode:page] no __myScriptCleanup (optional)",
        scriptId
      );
    }
  } catch (e) {
    console.error("[DonkeyCode:page] script error", scriptId, e);
  }
}

function donkeycodeCleanupMain(scriptId) {
  const g = typeof window !== "undefined" ? window : globalThis;
  const key = "__donkeycodeCleanups";
  const cleanups = g[key];
  if (cleanups && typeof cleanups[scriptId] === "function") {
    try {
      console.log("[DonkeyCode:page] cleanup invoked", scriptId);
      cleanups[scriptId]();
    } catch (e) {
      console.warn("[DonkeyCode:page] cleanup failed", scriptId, e);
    }
    delete cleanups[scriptId];
  } else {
    console.log("[DonkeyCode:page] no cleanup to run", scriptId);
  }
}

function rememberInjection(tabId, scriptId, injected) {
  if (!tabInjectedScripts.has(tabId)) tabInjectedScripts.set(tabId, new Set());
  const set = tabInjectedScripts.get(tabId);
  if (injected) set.add(scriptId);
  else set.delete(scriptId);
}

function forgetScriptEverywhere(scriptId) {
  for (const set of tabInjectedScripts.values()) {
    set.delete(scriptId);
  }
}

function forgetAllInjections() {
  tabInjectedScripts.clear();
}

async function getStoredScripts() {
  const data = await chrome.storage.local.get(STORAGE.SCRIPTS);
  const raw = data[STORAGE.SCRIPTS];
  return Array.isArray(raw) ? raw : [];
}

async function saveScripts(scripts) {
  await chrome.storage.local.set({ [STORAGE.SCRIPTS]: scripts });
}

async function getScriptSourceUrl() {
  const data = await chrome.storage.sync.get(STORAGE.SCRIPT_SOURCE);
  return data[STORAGE.SCRIPT_SOURCE] || DEFAULT_SCRIPT_SOURCE_URL;
}

async function getExtraUrls() {
  const data = await chrome.storage.sync.get(STORAGE.EXTRA_URLS);
  const list = data[STORAGE.EXTRA_URLS];
  if (!Array.isArray(list)) return [];
  return list;
}

async function fetchGitHubFileList(apiUrl) {
  const res = await fetch(apiUrl, {
    headers: { Accept: "application/vnd.github+json" },
  });
  if (!res.ok) throw new Error(`GitHub API ${res.status}: ${await res.text()}`);
  const json = await res.json();
  if (!Array.isArray(json)) throw new Error("GitHub API: expected array");
  return json;
}

async function fetchScriptText(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Fetch script ${res.status}: ${url}`);
  return await res.text();
}

/**
 * Discover .user.js from GitHub Contents API + optional raw URLs.
 */
async function loadScriptsFromRemote() {
  const sourceUrl = await getScriptSourceUrl();
  const extra = await getExtraUrls();
  log("loading script list from", sourceUrl, "extras", extra.length);

  const entries = [];

  try {
    const listing = await fetchGitHubFileList(sourceUrl);
    for (const item of listing) {
      if (item.type !== "file") continue;
      if (!/\.user\.js$/i.test(item.name || "")) continue;
      if (!item.download_url) continue;
      entries.push({
        url: item.download_url,
        name: item.name,
      });
    }
    log("GitHub listing: .user.js count", entries.length);
  } catch (e) {
    logError("GitHub listing failed", e);
    throw e;
  }

  for (const rawUrl of extra) {
    const u = (rawUrl || "").trim();
    if (!u) continue;
    entries.push({
      url: u,
      name: u.split("/").pop() || u,
    });
  }

  const prev = await getStoredScripts();
  const prevByUrl = new Map(prev.map((s) => [s.url, s]));

  const next = [];
  for (const e of entries) {
    const id = scriptIdFromUrl(e.url);
    const prevRow = prevByUrl.get(e.url);
    let text;
    try {
      text = await fetchScriptText(e.url);
      log("loaded script text", e.name, e.url, "chars", text.length);
    } catch (err) {
      logError("failed to fetch script", e.url, err);
      if (prevRow && prevRow.code) {
        text = prevRow.code;
        logWarn("using cached script body for", e.url);
      } else {
        continue;
      }
    }

    const meta = parseUserScript(text);
    const grants =
      meta.grants && meta.grants.length
        ? meta.grants
        : prevRow && prevRow.grants && prevRow.grants.length
          ? prevRow.grants
          : meta.grants || [];
    const connects =
      meta.connects && meta.connects.length
        ? meta.connects
        : prevRow && prevRow.connects && prevRow.connects.length
          ? prevRow.connects
          : meta.connects || [];
    const userScriptName =
      meta.userScriptName ||
      (prevRow && prevRow.userScriptName) ||
      "";
    next.push({
      id,
      url: e.url,
      name: e.name,
      userScriptName,
      enabled: prevRow ? prevRow.enabled !== false : false,
      matches: meta.matches,
      excludes: meta.excludes,
      grants,
      connects,
      code: meta.body,
    });
  }

  await saveScripts(next);
  await chrome.storage.local.set({
    [STORAGE.LAST_FETCH]: Date.now(),
  });

  forgetAllInjections();
  log("scripts saved", next.length);
  updateInstallBadge().catch(() => {});
  return next;
}

async function ensureDailyAlarm() {
  const existing = await chrome.alarms.get(ALARM_DAILY);
  if (!existing) {
    chrome.alarms.create(ALARM_DAILY, { periodInMinutes: 24 * 60 });
    log("created daily alarm");
  }
}

chrome.alarms.onAlarm.addListener((alarm) => {
  if (alarm.name === ALARM_DAILY) {
    log("daily alarm: refreshing scripts");
    loadScriptsFromRemote().catch((e) => logError("daily refresh failed", e));
  }
});

chrome.runtime.onStartup.addListener(() => {
  log("onStartup: refresh scripts");
  ensureHostAccessAndBridge().catch((e) => logError("startup host/bridge", e));
  loadScriptsFromRemote()
    .then(() => updateInstallBadge())
    .catch((e) => {
      logError("startup refresh failed", e);
      updateInstallBadge();
    });
});

chrome.runtime.onInstalled.addListener((details) => {
  log("onInstalled: refresh scripts + alarm", details && details.reason);
  ensureDailyAlarm();
  ensureHostAccessAndBridge().catch((e) => logError("install host/bridge", e));
  loadScriptsFromRemote()
    .then(() => updateInstallBadge())
    .catch((e) => {
      logError("install refresh failed", e);
      updateInstallBadge();
    });
  if (details.reason === "install" || details.reason === "update") {
    chrome.storage.local
      .set({ [STORAGE.PENDING_INITIAL_SESSION_PULL]: true })
      .catch((e) => logWarn("pending initial session pull", e));
  }
  if (details.reason === "install") {
    const url = chrome.runtime.getURL("welcome.html");
    chrome.tabs.create({ url }).catch((e) => logWarn("welcome tab", e));
  } else {
    updateInstallBadge().catch(() => {});
  }
});

chrome.tabs.onRemoved.addListener((tabId) => {
  tabInjectedScripts.delete(tabId);
});

/**
 * @param {number} tabId
 * @param {string} url
 */
async function syncTabScripts(tabId, url) {
  if (!url || url.startsWith("chrome://") || url.startsWith("devtools://"))
    return;

  if (!(await hasOriginAccessForUrl(url))) {
    log("skip inject (no optional host permission for origin)", url);
    return;
  }

  const scripts = await getStoredScripts();
  for (const script of scripts) {
    if (!script.enabled) continue;
    if (!script.code) continue;
    if (!scriptMatchesUrl(script, url)) continue;

    const set = tabInjectedScripts.get(tabId) || new Set();
    if (set.has(script.id)) continue;

    try {
      await chrome.scripting.executeScript({
        target: { tabId, allFrames: false },
        world: "MAIN",
        func: donkeycodeInjectMain,
        args: [
          {
            id: script.id,
            code: script.code,
            grants: script.grants || [],
            connects: script.connects || [],
          },
        ],
      });
      rememberInjection(tabId, script.id, true);
      log("injected script", script.id, script.name, "tab", tabId, url);
    } catch (e) {
      logError("inject failed", script.id, tabId, e);
    }
  }
}

chrome.tabs.onUpdated.addListener((tabId, changeInfo, tab) => {
  if (changeInfo.status !== "complete" || !tab.url) return;
  tabInjectedScripts.delete(tabId);
  syncTabScripts(tabId, tab.url).catch((e) => logError("syncTabScripts", e));
});

/**
 * Re-run matching for all tabs (after toggle or refresh).
 */
async function resyncAllTabs() {
  const tabs = await chrome.tabs.query({});
  for (const t of tabs) {
    if (!t.id || !t.url) continue;
    await syncTabScripts(t.id, t.url);
  }
}

async function cleanupScriptEverywhere(scriptId) {
  const tabs = await chrome.tabs.query({});
  for (const t of tabs) {
    if (!t.id) continue;
    try {
      await chrome.scripting.executeScript({
        target: { tabId: t.id, allFrames: false },
        world: "MAIN",
        func: donkeycodeCleanupMain,
        args: [scriptId],
      });
      log("cleanup dispatched", scriptId, "tab", t.id);
    } catch (e) {
      logWarn("cleanup failed for tab", t.id, e);
    }
    const set = tabInjectedScripts.get(t.id);
    if (set) set.delete(scriptId);
  }
}

async function toggleScript(scriptId, enabled) {
  const scripts = await getStoredScripts();
  const idx = scripts.findIndex((s) => s.id === scriptId);
  if (idx < 0) throw new Error("Script not found");
  scripts[idx].enabled = enabled;
  await saveScripts(scripts);
  log("toggle script", scriptId, enabled);

  if (!enabled) {
    await cleanupScriptEverywhere(scriptId);
  } else {
    forgetScriptEverywhere(scriptId);
    await resyncAllTabs();
  }
  updateInstallBadge().catch(() => {});
}

/** OpsSuite worksheet tabs — stable restore order + stagger helps server-side numbering. */
const WORKSHEET_HOST = "opssuitemain.swacorp.com";
const WORKSHEET_PATH_MARK = "/widgets/worksheet";

function isOpsSuiteWorksheetUrl(url) {
  if (!url || typeof url !== "string") return false;
  try {
    const u = new URL(url);
    return (
      u.hostname === WORKSHEET_HOST &&
      u.pathname.toLowerCase().indexOf(WORKSHEET_PATH_MARK) !== -1
    );
  } catch (e) {
    return false;
  }
}

function sessionHasWorksheetTabs(snap) {
  if (!snap || !Array.isArray(snap.windows)) return false;
  for (const w of snap.windows) {
    for (const t of w.tabs || []) {
      if (isOpsSuiteWorksheetUrl(t.url)) return true;
    }
  }
  return false;
}

function worksheetPrimaryUrlForWindow(w) {
  for (const t of w.tabs || []) {
    if (isOpsSuiteWorksheetUrl(t.url)) return String(t.url);
  }
  return "";
}

/**
 * Deterministic order: optional `restoreOrder` (lower first), then worksheet URL,
 * then original index. Edit JSON to set per-window `restoreOrder` if needed.
 */
function sortWindowsForRestore(windows) {
  return windows
    .map((w, i) => ({ w, i }))
    .sort((A, B) => {
      const a = A.w;
      const b = B.w;
      const roA = typeof a.restoreOrder === "number" ? a.restoreOrder : 1e9;
      const roB = typeof b.restoreOrder === "number" ? b.restoreOrder : 1e9;
      if (roA !== roB) return roA - roB;
      const wa = worksheetPrimaryUrlForWindow(a);
      const wb = worksheetPrimaryUrlForWindow(b);
      if (wa && wb && wa !== wb) return wa.localeCompare(wb);
      if (wa && !wb) return -1;
      if (!wa && wb) return 1;
      return A.i - B.i;
    })
    .map((x) => x.w);
}

function delayMs(ms) {
  return new Promise(function (resolve) {
    setTimeout(resolve, ms);
  });
}

function normalizeSessionSnapshot(snap) {
  if (!snap || !Array.isArray(snap.windows)) {
    const empty = { windows: [], _meta: { updatedAt: 0 } };
    if (snap && snap._meta && typeof snap._meta === "object") {
      empty._meta = {
        updatedAt: Number(snap._meta.updatedAt) || 0,
      };
      if (typeof snap._meta.worksheetStaggerMs === "number") {
        empty._meta.worksheetStaggerMs = snap._meta.worksheetStaggerMs;
      }
    }
    return empty;
  }
  const windows = snap.windows.map((w, wi) => {
    const id =
      w.id && String(w.id).trim()
        ? String(w.id)
        : "w_" + wi + "_" + Math.random().toString(36).slice(2, 9);
    const tabs = (w.tabs || []).map((t, ti) => ({
      url: t.url != null ? String(t.url) : "",
      active: !!t.active,
      index: typeof t.index === "number" ? t.index : ti,
      pinned: !!t.pinned,
    }));
    const win = {
      id,
      left: w.left,
      top: w.top,
      width: w.width,
      height: w.height,
      state: w.state,
      focused: w.focused,
      tabs,
    };
    if (typeof w.restoreOrder === "number") win.restoreOrder = w.restoreOrder;
    return win;
  });
  const out = { windows };
  if (snap._meta && typeof snap._meta === "object") {
    out._meta = { updatedAt: Number(snap._meta.updatedAt) || 0 };
    if (typeof snap._meta.worksheetStaggerMs === "number") {
      out._meta.worksheetStaggerMs = snap._meta.worksheetStaggerMs;
    }
  } else {
    out._meta = { updatedAt: 0 };
  }
  return out;
}

function touchSessionMeta(snap) {
  const n = normalizeSessionSnapshot(snap);
  const prev = n._meta && typeof n._meta === "object" ? n._meta : {};
  n._meta = { ...prev, updatedAt: Date.now() };
  return n;
}

const DEFAULT_SESSION_FOLDER = "__default__";

function normalizeFolderKey(name) {
  const t = (name || "").trim().replace(/\\/g, "/");
  if (!t) return DEFAULT_SESSION_FOLDER;
  return t.replace(/^\/+|\/+$/g, "") || DEFAULT_SESSION_FOLDER;
}

function folderGithubSegments(folderEntry, folderKey) {
  const fk = normalizeFolderKey(folderKey);
  const manual = (folderEntry && folderEntry.githubRelativePath
    ? String(folderEntry.githubRelativePath)
    : ""
  )
    .trim()
    .replace(/\\/g, "/");
  if (manual) {
    return manual
      .split("/")
      .map((s) => s.trim())
      .filter(Boolean);
  }
  if (fk === DEFAULT_SESSION_FOLDER) return [];
  return fk
    .split("/")
    .map((s) => s.trim())
    .filter(Boolean);
}

/**
 * Session snapshots are large; chrome.storage.sync limits each key to ~8KB.
 * Store session folder data in chrome.storage.local (much higher per-item limits).
 * One-time migration from sync (and legacy flat SESSIONS) into local.
 */
async function migrateSessionStorageToLocalIfNeeded() {
  const done = await chrome.storage.local.get(STORAGE.SESSION_STORAGE_MIGRATED);
  if (done[STORAGE.SESSION_STORAGE_MIGRATED]) return;

  const syncPack = await chrome.storage.sync.get([
    STORAGE.SESSION_FOLDERS_V2,
    STORAGE.CURRENT_SESSION_FOLDER,
    STORAGE.SESSIONS,
  ]);
  let folders = syncPack[STORAGE.SESSION_FOLDERS_V2];
  if (!folders || typeof folders !== "object" || Array.isArray(folders)) {
    folders = {};
  }

  const legacy = syncPack[STORAGE.SESSIONS];
  if (legacy && typeof legacy === "object" && Object.keys(legacy).length) {
    if (!folders[DEFAULT_SESSION_FOLDER]) folders[DEFAULT_SESSION_FOLDER] = { sessions: {} };
    const existing = folders[DEFAULT_SESSION_FOLDER].sessions || {};
    folders[DEFAULT_SESSION_FOLDER].sessions = { ...legacy, ...existing };
    log("migration: merged legacy flat sessions into", DEFAULT_SESSION_FOLDER);
  }

  if (!folders[DEFAULT_SESSION_FOLDER]) {
    folders[DEFAULT_SESSION_FOLDER] = { sessions: {} };
  }

  let cur = (syncPack[STORAGE.CURRENT_SESSION_FOLDER] || "").trim() || DEFAULT_SESSION_FOLDER;
  cur = normalizeFolderKey(cur);
  if (!folders[cur]) folders[cur] = { sessions: {} };

  await chrome.storage.local.set({
    [STORAGE.SESSION_FOLDERS_V2]: folders,
    [STORAGE.CURRENT_SESSION_FOLDER]: cur,
    [STORAGE.SESSION_STORAGE_MIGRATED]: true,
  });

  try {
    await chrome.storage.sync.remove([
      STORAGE.SESSION_FOLDERS_V2,
      STORAGE.CURRENT_SESSION_FOLDER,
      STORAGE.SESSIONS,
      STORAGE.SESSIONS_LEGACY_MIGRATED,
    ]);
  } catch (e) {
    logWarn("migration: could not remove old sync session keys", e);
  }

  log("sessions storage migrated to chrome.storage.local");
}

async function getSessionFoldersState() {
  await migrateSessionStorageToLocalIfNeeded();
  const d = await chrome.storage.local.get([
    STORAGE.SESSION_FOLDERS_V2,
    STORAGE.CURRENT_SESSION_FOLDER,
  ]);
  let folders = d[STORAGE.SESSION_FOLDERS_V2];
  if (!folders || typeof folders !== "object" || Array.isArray(folders)) {
    folders = {};
  }
  if (!folders[DEFAULT_SESSION_FOLDER]) {
    folders[DEFAULT_SESSION_FOLDER] = { sessions: {} };
  }
  let cur = (d[STORAGE.CURRENT_SESSION_FOLDER] || "").trim() || DEFAULT_SESSION_FOLDER;
  cur = normalizeFolderKey(cur);
  if (!folders[cur]) folders[cur] = { sessions: {} };
  return { folders, currentKey: cur };
}

async function getCurrentSessionFolderKey() {
  const { currentKey } = await getSessionFoldersState();
  return currentKey;
}

async function getSessionsMapForFolder(folderKey) {
  const { folders } = await getSessionFoldersState();
  const fk = normalizeFolderKey(folderKey);
  const entry = folders[fk] || { sessions: {} };
  const raw =
    entry.sessions &&
    typeof entry.sessions === "object" &&
    !Array.isArray(entry.sessions)
      ? entry.sessions
      : {};
  const out = {};
  for (const k of Object.keys(raw)) {
    out[k] = normalizeSessionSnapshot(raw[k]);
  }
  return out;
}

async function setSessionsMapForFolder(folderKey, sessionsObj) {
  const { folders } = await getSessionFoldersState();
  const fk = normalizeFolderKey(folderKey);
  if (!folders[fk]) folders[fk] = { sessions: {} };
  const map =
    sessionsObj && typeof sessionsObj === "object" && !Array.isArray(sessionsObj)
      ? sessionsObj
      : {};
  folders[fk].sessions = map;
  await chrome.storage.local.set({ [STORAGE.SESSION_FOLDERS_V2]: folders });
}

async function getGithubPathForFolder(folderKey) {
  const base = await getGithubSettings();
  const { folders } = await getSessionFoldersState();
  const fk = normalizeFolderKey(folderKey);
  const entry = folders[fk] || {};
  const segs = folderGithubSegments(entry, fk);
  const path = joinGithubRepoPath(base.sessionsRoot, ...segs, SESSION_JSON_FILENAME);
  return { ...base, path };
}

async function getSessionsMap() {
  const fk = await getCurrentSessionFolderKey();
  return getSessionsMapForFolder(fk);
}

async function setSessionsMap(sessionsObj) {
  const fk = await getCurrentSessionFolderKey();
  await setSessionsMapForFolder(fk, sessionsObj);
}

function mergeSessionsByTimestamp(localMap, remoteMap) {
  const names = new Set([
    ...Object.keys(localMap || {}),
    ...Object.keys(remoteMap || {}),
  ]);
  const merged = {};
  for (const name of names) {
    const L = localMap[name];
    const R = remoteMap[name];
    const tL = L && L._meta ? Number(L._meta.updatedAt) || 0 : 0;
    const tR = R && R._meta ? Number(R._meta.updatedAt) || 0 : 0;
    if (!L) merged[name] = normalizeSessionSnapshot(R);
    else if (!R) merged[name] = normalizeSessionSnapshot(L);
    else if (tR > tL) merged[name] = normalizeSessionSnapshot(R);
    else merged[name] = normalizeSessionSnapshot(L);
  }
  return merged;
}

function sessionsToGithubFilePayload(sessionsMap) {
  return {
    version: 1,
    updatedAt: Date.now(),
    sessions: sessionsMap,
  };
}

function sessionsFromGithubFilePayload(parsed) {
  if (!parsed || typeof parsed !== "object") return {};
  if (parsed.sessions && typeof parsed.sessions === "object") {
    const out = {};
    for (const [k, v] of Object.entries(parsed.sessions)) {
      out[k] = normalizeSessionSnapshot(v);
    }
    return out;
  }
  return {};
}

function utf8ToBase64(str) {
  return btoa(unescape(encodeURIComponent(str)));
}

function base64ToUtf8(b64) {
  return decodeURIComponent(escape(atob(b64)));
}

async function githubApiRequest(path, options, token) {
  const url = path.startsWith("http") ? path : "https://api.github.com" + path;
  const headers = {
    Accept: "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
    ...(options.headers || {}),
  };
  if (token) headers.Authorization = "Bearer " + token;
  const res = await fetch(url, { ...options, headers });
  const text = await res.text();
  let json = null;
  try {
    json = text ? JSON.parse(text) : null;
  } catch (e) {
    json = null;
  }
  if (!res.ok) {
    const err = new Error(
      (json && json.message) || text || "HTTP " + res.status
    );
    err.status = res.status;
    throw err;
  }
  return json;
}

async function getGithubSettings() {
  await migrateGithubSessionsRootIfNeeded();
  const data = await chrome.storage.local.get([
    STORAGE.GITHUB_PAT,
    STORAGE.GITHUB_OWNER,
    STORAGE.GITHUB_REPO,
    STORAGE.GITHUB_BRANCH,
    STORAGE.GITHUB_PATH,
    STORAGE.GITHUB_SESSIONS_ROOT,
  ]);
  const baked = self.BAKED_GITHUB_DEFAULTS || {};
  const token =
    (data[STORAGE.GITHUB_PAT] || "").trim() || String(baked.token || "").trim();
  const owner =
    (data[STORAGE.GITHUB_OWNER] || "").trim() || String(baked.owner || "").trim();
  const repo =
    (data[STORAGE.GITHUB_REPO] || "").trim() || String(baked.repo || "").trim();
  const branchRaw =
    (data[STORAGE.GITHUB_BRANCH] || "").trim() ||
    String(baked.branch || "main").trim() ||
    "main";
  const branch = branchRaw || "main";
  const pathRaw =
    (data[STORAGE.GITHUB_PATH] || "").trim() ||
    String(baked.path || "sessions/donkeycode-sessions.json").trim();
  const legacyPath = (pathRaw || "sessions/donkeycode-sessions.json").replace(
    /^\/+/,
    ""
  );
  let sessionsRoot = (data[STORAGE.GITHUB_SESSIONS_ROOT] || "").trim();
  if (!sessionsRoot) {
    sessionsRoot = deriveSessionsRootFromLegacyPath(legacyPath);
  }
  const path = defaultSessionFilePathForRoot(sessionsRoot);
  return { token, owner, repo, branch, path, sessionsRoot };
}

async function fetchGithubSessionsFile(settings) {
  const { token, owner, repo, branch, path } = settings;
  if (!token || !owner || !repo) throw new Error("GitHub owner, repo, and token required");
  const pathSeg = path
    .split("/")
    .map((p) => encodeURIComponent(p))
    .join("/");
  const apiPath =
    "/repos/" +
    encodeURIComponent(owner) +
    "/" +
    encodeURIComponent(repo) +
    "/contents/" +
    pathSeg +
    "?ref=" +
    encodeURIComponent(branch);
  let json;
  try {
    json = await githubApiRequest(apiPath, { method: "GET" }, token);
  } catch (e) {
    if (e && e.status === 404) return null;
    throw e;
  }
  if (!json || json.type !== "file" || !json.content) {
    throw new Error("Unexpected GitHub API response for file");
  }
  const raw = base64ToUtf8(json.content.replace(/\s/g, ""));
  const parsed = JSON.parse(raw);
  return { sha: json.sha, sessions: sessionsFromGithubFilePayload(parsed) };
}

async function putGithubSessionsFile(settings, bodyObj, shaOrNull) {
  const { token, owner, repo, branch, path } = settings;
  const pathSeg = path
    .split("/")
    .map((p) => encodeURIComponent(p))
    .join("/");
  const apiPath =
    "/repos/" +
    encodeURIComponent(owner) +
    "/" +
    encodeURIComponent(repo) +
    "/contents/" +
    pathSeg;
  const content = utf8ToBase64(JSON.stringify(bodyObj, null, 2));
  const payload = {
    message: "DonkeyCode: sync sessions",
    content,
    branch,
  };
  if (shaOrNull) payload.sha = shaOrNull;
  await githubApiRequest(
    apiPath,
    {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload),
    },
    token
  );
}

async function githubListDirectory(settings, relativePath) {
  const { token, owner, repo, branch } = settings;
  const prefix = (relativePath || "").trim().replace(/^\/+/, "");
  const contentsPath = prefix
    ? "/contents/" + prefix.split("/").map((p) => encodeURIComponent(p)).join("/")
    : "/contents";
  const apiPath =
    "/repos/" +
    encodeURIComponent(owner) +
    "/" +
    encodeURIComponent(repo) +
    contentsPath +
    "?ref=" +
    encodeURIComponent(branch);
  const json = await githubApiRequest(apiPath, { method: "GET" }, token);
  return Array.isArray(json) ? json : [];
}

/**
 * Subfolders under sessions root that contain donkeycode-sessions.json (Git “folders”).
 */
async function discoverGithubSessionFolderKeys() {
  const gh = await getGithubSettings();
  if (!gh.token || !gh.owner || !gh.repo) {
    throw new Error("Configure GitHub owner, repo, and personal access token.");
  }
  const root = (gh.sessionsRoot || "").trim();
  const items = await githubListDirectory(gh, root);
  const keys = [];
  for (const it of items) {
    if (!it || it.type !== "dir" || !it.name) continue;
    if (it.name.startsWith(".")) continue;
    const subPath = joinGithubRepoPath(root, it.name);
    try {
      const subItems = await githubListDirectory(gh, subPath);
      const hasFile = subItems.some(
        (x) => x && x.type === "file" && x.name === SESSION_JSON_FILENAME
      );
      if (hasFile) keys.push(it.name);
    } catch (e) {
      logWarn("discover: could not list", subPath, e);
    }
  }
  keys.sort();
  return keys;
}

/**
 * Add local session folders for each remote subfolder that has a sessions file.
 */
async function discoverAndCreateLocalSessionFolders() {
  const keys = await discoverGithubSessionFolderKeys();
  const { folders, currentKey } = await getSessionFoldersState();
  const had = new Set(Object.keys(folders));
  let changed = false;
  for (const name of keys) {
    const fk = normalizeFolderKey(name);
    if (fk === DEFAULT_SESSION_FOLDER) continue;
    if (!folders[fk]) {
      folders[fk] = { sessions: {}, githubRelativePath: "" };
      changed = true;
    }
  }
  if (changed) {
    await chrome.storage.local.set({
      [STORAGE.SESSION_FOLDERS_V2]: folders,
      [STORAGE.CURRENT_SESSION_FOLDER]: currentKey,
    });
    log("GitHub discovery: merged folder keys", keys.join(", "));
  }
  const newLocalFolders = keys.filter((k) => !had.has(normalizeFolderKey(k)));
  return { discovered: keys, newLocalFolders };
}

async function githubPullAllFoldersMerge() {
  const { folders } = await getSessionFoldersState();
  const folderKeys = Object.keys(folders).sort();
  const errors = [];
  for (const fk of folderKeys) {
    try {
      const settings = await getGithubPathForFolder(fk);
      let remoteSessions = {};
      const file = await fetchGithubSessionsFile(settings);
      if (!file) {
        log("GitHub pull: no file for folder", fk, "path", settings.path);
      } else {
        remoteSessions = file.sessions || {};
      }
      const local = await getSessionsMapForFolder(fk);
      const merged = mergeSessionsByTimestamp(local, remoteSessions);
      await setSessionsMapForFolder(fk, merged);
      log(
        "GitHub pull merged folder",
        fk,
        Object.keys(merged).length,
        "sessions",
        "path",
        settings.path
      );
    } catch (e) {
      const msg = String(e && e.message ? e.message : e);
      errors.push(fk + ": " + msg);
      logWarn("GitHub pull failed for folder", fk, e);
    }
  }
  return errors;
}

async function githubDeleteRepoFile(settings, sha) {
  const { token, owner, repo, branch, path } = settings;
  if (!sha) throw new Error("Missing file sha for GitHub delete");
  const pathSeg = path
    .split("/")
    .map((p) => encodeURIComponent(p))
    .join("/");
  const apiPath =
    "/repos/" +
    encodeURIComponent(owner) +
    "/" +
    encodeURIComponent(repo) +
    "/contents/" +
    pathSeg;
  await githubApiRequest(
    apiPath,
    {
      method: "DELETE",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        message: "DonkeyCode: remove session folder file",
        sha,
        branch,
      }),
    },
    token
  );
}

/**
 * Create an empty sessions JSON on GitHub if missing (so the folder path exists in the repo).
 */
async function ensureGithubSessionsPlaceholderForFolder(folderKey) {
  const settings = await getGithubPathForFolder(folderKey);
  if (!settings.token || !settings.owner || !settings.repo) {
    return { skipped: true };
  }
  const existing = await fetchGithubSessionsFile(settings);
  if (existing) return { skipped: false, created: false };
  const empty = sessionsToGithubFilePayload({});
  await putGithubSessionsFile(settings, empty, null);
  log("GitHub: created placeholder sessions file for folder", folderKey, settings.path);
  return { skipped: false, created: true, path: settings.path };
}

/**
 * If base path looks like the bundled test fixtures layout, ensure local folders
 * alpha…epsilon exist with matching GitHub subfolders so each remote file has a target.
 */
async function ensureTestFixtureFoldersIfNeeded() {
  const gh = await getGithubSettings();
  const p = (gh.sessionsRoot || "").toLowerCase();
  if (p.indexOf("donkeycode-test-fixtures") === -1) return;
  const { folders } = await getSessionFoldersState();
  const testNames = ["alpha", "beta", "gamma", "delta", "epsilon"];
  let changed = false;
  for (const name of testNames) {
    if (!folders[name]) {
      folders[name] = { sessions: {}, githubRelativePath: name };
      changed = true;
    }
  }
  if (changed) {
    await chrome.storage.local.set({ [STORAGE.SESSION_FOLDERS_V2]: folders });
    log("ensureTestFixtureFolders: created folders", testNames.join(", "));
  }
}

/**
 * Pull: discover subfolders on GitHub under the sessions root, merge them into local
 * folder list, then merge remote JSON into each local folder (including Default).
 */
async function githubSyncPull() {
  const gh = await getGithubSettings();
  if (!gh.token || !gh.owner || !gh.repo) {
    throw new Error("Configure GitHub owner, repo, and personal access token in Settings.");
  }
  await ensureTestFixtureFoldersIfNeeded();
  let discovery = { discovered: [], newLocalFolders: [] };
  try {
    discovery = await discoverAndCreateLocalSessionFolders();
  } catch (e) {
    logWarn("GitHub folder discovery failed (continuing with local folders only)", e);
    discovery = {
      discovered: [],
      newLocalFolders: [],
      discoveryError: String(e && e.message ? e.message : e),
    };
  }
  const errors = await githubPullAllFoldersMerge();
  if (discovery.discoveryError) {
    errors.unshift("(discovery) " + discovery.discoveryError);
  }

  await chrome.storage.local.set({
    [STORAGE.GITHUB_SYNC_LAST_ERROR]: errors.length ? errors.join(" | ") : "",
    [STORAGE.GITHUB_SYNC_LAST_OK]: Date.now(),
  });

  const curFk = await getCurrentSessionFolderKey();
  const curSessions = Object.keys(await getSessionsMapForFolder(curFk)).sort();
  log("GitHub pull all folders done; current", curFk, "count", curSessions.length);
  return {
    sessions: curSessions,
    pullErrors: errors,
    discoveredRemoteFolders: discovery.discovered || [],
    newLocalFolders: discovery.newLocalFolders || [],
  };
}

async function githubPushSingleFolder(folderKey) {
  const fk = normalizeFolderKey(folderKey);
  const settings = await getGithubPathForFolder(fk);
  if (!settings.token || !settings.owner || !settings.repo) {
    throw new Error("Configure GitHub owner, repo, and personal access token in Settings.");
  }
  const local = await getSessionsMapForFolder(fk);
  let sha = null;
  let remoteSessions = {};
  const file = await fetchGithubSessionsFile(settings);
  if (file) {
    remoteSessions = file.sessions || {};
    sha = file.sha;
  }
  const merged = mergeSessionsByTimestamp(local, remoteSessions);
  await setSessionsMapForFolder(fk, merged);
  const payload = sessionsToGithubFilePayload(merged);
  await putGithubSessionsFile(settings, payload, sha);
  log("GitHub push ok", Object.keys(merged).length, "sessions", "folder", fk, settings.path);
  return { folderKey: fk, sessions: Object.keys(merged).sort() };
}

async function githubSyncPush() {
  const fk = await getCurrentSessionFolderKey();
  const result = await githubPushSingleFolder(fk);
  await chrome.storage.local.set({
    [STORAGE.GITHUB_SYNC_LAST_ERROR]: "",
    [STORAGE.GITHUB_SYNC_LAST_OK]: Date.now(),
  });
  return { sessions: result.sessions };
}

async function githubSyncPushAll() {
  const gh = await getGithubSettings();
  if (!gh.token || !gh.owner || !gh.repo) {
    throw new Error("Configure GitHub owner, repo, and personal access token in Settings.");
  }
  await ensureTestFixtureFoldersIfNeeded();
  const { folders } = await getSessionFoldersState();
  const folderKeys = Object.keys(folders).sort();
  const errors = [];
  for (const fk of folderKeys) {
    try {
      await githubPushSingleFolder(fk);
    } catch (e) {
      const msg = String(e && e.message ? e.message : e);
      errors.push(fk + ": " + msg);
      logWarn("GitHub push failed for folder", fk, e);
    }
  }
  await chrome.storage.local.set({
    [STORAGE.GITHUB_SYNC_LAST_ERROR]: errors.length ? errors.join(" | ") : "",
    [STORAGE.GITHUB_SYNC_LAST_OK]: Date.now(),
  });
  const curFk = await getCurrentSessionFolderKey();
  const curSessions = Object.keys(await getSessionsMapForFolder(curFk)).sort();
  log("GitHub push all folders done; errors", errors.length);
  return { sessions: curSessions, pushErrors: errors };
}

/**
 * Discover remote folders, pull merge all, then push all (uploads new empty JSONs too).
 */
async function githubSyncAll() {
  const gh = await getGithubSettings();
  if (!gh.token || !gh.owner || !gh.repo) {
    throw new Error("Configure GitHub owner, repo, and personal access token in Settings.");
  }
  await ensureTestFixtureFoldersIfNeeded();
  let discovery = { discovered: [], newLocalFolders: [] };
  try {
    discovery = await discoverAndCreateLocalSessionFolders();
  } catch (e) {
    logWarn("sync all: discovery failed", e);
    discovery = {
      discovered: [],
      newLocalFolders: [],
      discoveryError: String(e && e.message ? e.message : e),
    };
  }
  const pullErrors = await githubPullAllFoldersMerge();
  if (discovery.discoveryError) {
    pullErrors.unshift("(discovery) " + discovery.discoveryError);
  }
  const pushRes = await githubSyncPushAll();
  const allErrors = pullErrors.concat(pushRes.pushErrors || []);
  await chrome.storage.local.set({
    [STORAGE.GITHUB_SYNC_LAST_ERROR]: allErrors.length ? allErrors.join(" | ") : "",
    [STORAGE.GITHUB_SYNC_LAST_OK]: Date.now(),
  });
  const curFk = await getCurrentSessionFolderKey();
  const curSessions = Object.keys(await getSessionsMapForFolder(curFk)).sort();
  return {
    sessions: curSessions,
    pullErrors,
    pushErrors: pushRes.pushErrors || [],
    discoveredRemoteFolders: discovery.discovered || [],
    newLocalFolders: discovery.newLocalFolders || [],
  };
}

/**
 * After local session changes: push to GitHub when owner/repo/token are set.
 * Skips quietly if not configured; logs and records error on failure (local data still saved).
 */
async function maybeAutoPushSessionsToGithub() {
  const gh = await getGithubSettings();
  if (!gh.token || !gh.owner || !gh.repo) {
    return { skipped: true };
  }
  try {
    const result = await githubSyncPush();
    return { skipped: false, ok: true, sessions: result.sessions };
  } catch (e) {
    const msg = String(e && e.message ? e.message : e);
    await chrome.storage.local.set({
      [STORAGE.GITHUB_SYNC_LAST_ERROR]: msg,
    });
    logWarn("auto GitHub session push failed", e);
    return { skipped: false, ok: false, error: msg };
  }
}

async function captureSessionSnapshot() {
  const wins = await chrome.windows.getAll({ populate: true, windowTypes: ["normal"] });
  const snapshot = {
    windows: wins.map((w, wi) => ({
      id: "w_" + wi + "_" + Date.now().toString(36),
      left: w.left,
      top: w.top,
      width: w.width,
      height: w.height,
      state: w.state,
      focused: w.focused,
      tabs: (w.tabs || []).map((t) => ({
        url: t.url || "",
        active: t.active,
        index: t.index,
        pinned: t.pinned,
      })),
    })),
  };
  return normalizeSessionSnapshot(snapshot);
}

async function saveSession(name, snapshotOverride) {
  const trimmed = (name || "").trim();
  if (!trimmed) throw new Error("Session name required");
  let snap;
  if (snapshotOverride && typeof snapshotOverride === "object") {
    snap = touchSessionMeta(normalizeSessionSnapshot(snapshotOverride));
  } else {
    snap = touchSessionMeta(await captureSessionSnapshot());
  }
  const fk = await getCurrentSessionFolderKey();
  const sessions = await getSessionsMapForFolder(fk);
  sessions[trimmed] = snap;
  try {
    await setSessionsMapForFolder(fk, sessions);
  } catch (e) {
    if (e && e.message && String(e.message).toLowerCase().includes("quota")) {
      logError(
        "sync quota exceeded saving session; reduce open tabs or remove old sessions",
        e
      );
    }
    throw e;
  }
  log("session saved", trimmed, "windows", snap.windows.length);
}

async function restoreSessionInternal(name) {
  const trimmed = (name || "").trim();
  if (!trimmed) throw new Error("Session name required");
  const fk = await getCurrentSessionFolderKey();
  const sessions = await getSessionsMapForFolder(fk);
  const snap = normalizeSessionSnapshot(sessions[trimmed]);
  if (!snap.windows.length) throw new Error("Session not found");

  const ordered = sortWindowsForRestore(snap.windows);
  const hasWs = sessionHasWorksheetTabs(snap);
  let stagger = 0;
  if (hasWs) {
    if (snap._meta && typeof snap._meta.worksheetStaggerMs === "number") {
      stagger = Math.max(0, snap._meta.worksheetStaggerMs);
    } else {
      stagger = 800;
    }
  }

  for (let wi = 0; wi < ordered.length; wi++) {
    const w = ordered[wi];
    if (wi > 0 && stagger > 0) {
      log("worksheet stagger delay", stagger, "ms before window", wi + 1);
      await delayMs(stagger);
    }
    const urls = (w.tabs || [])
      .sort((a, b) => (a.index || 0) - (b.index || 0))
      .map((t) => t.url)
      .filter(
        (u) =>
          u &&
          !u.startsWith("chrome-extension:") &&
          /^https?:\/\//i.test(u)
      );
    if (urls.length === 0) continue;

    const created = await chrome.windows.create({
      url: urls,
      left: w.left,
      top: w.top,
      width: w.width,
      height: w.height,
      focused: !!w.focused,
      state: w.state === "minimized" || w.state === "maximized" ? w.state : undefined,
    });

    if (created && created.tabs && w.tabs) {
      const sortedTabs = (w.tabs || []).slice().sort((a, b) => (a.index || 0) - (b.index || 0));
      const activeIndex = sortedTabs.findIndex((t) => t.active);
      if (activeIndex >= 0 && created.tabs[activeIndex]) {
        try {
          await chrome.tabs.update(created.tabs[activeIndex].id, { active: true });
        } catch (e) {
          logWarn("could not activate tab", e);
        }
      }
    }
  }
  log("session restored", trimmed, "windows", ordered.length, "staggerMs", stagger);
}

async function restoreSession(name) {
  await restoreSessionInternal(name);
}

async function openLoginWindowsThenQueueRestore(sessionName) {
  const trimmed = (sessionName || "").trim();
  if (!trimmed) throw new Error("Session name required");
  await chrome.storage.local.set({
    [STORAGE.PENDING_RESTORE]: trimmed,
  });
  const width = 820;
  const height = 880;
  const top = 32;
  const left0 = 40;
  const gap = 12;
  const w1 = await chrome.windows.create({
    url: LOGIN_WINDOW_URLS[0],
    focused: true,
    type: "normal",
    width,
    height,
    left: left0,
    top,
  });
  let left2 = left0 + width + gap;
  try {
    const b1 = await chrome.windows.get(w1.id);
    if (b1.left != null && b1.width != null) {
      left2 = b1.left + b1.width + gap;
    }
  } catch (e) {
    logWarn("could not read first login window bounds", e);
  }
  await chrome.windows.create({
    url: LOGIN_WINDOW_URLS[1],
    focused: false,
    type: "normal",
    width,
    height,
    left: left2,
    top,
  });
  log("login windows opened side by side; pending restore", trimmed);
}

async function completePendingRestore() {
  const data = await chrome.storage.local.get(STORAGE.PENDING_RESTORE);
  const name = data[STORAGE.PENDING_RESTORE];
  if (!name || !String(name).trim()) {
    throw new Error("No session is waiting. Use Login First, then Continue.");
  }
  await chrome.storage.local.remove(STORAGE.PENDING_RESTORE);
  await restoreSessionInternal(String(name).trim());
  log("pending restore completed", name);
}

async function getPendingRestore() {
  const data = await chrome.storage.local.get(STORAGE.PENDING_RESTORE);
  const name = data[STORAGE.PENDING_RESTORE];
  return name ? String(name) : null;
}

async function clearPendingRestore() {
  await chrome.storage.local.remove(STORAGE.PENDING_RESTORE);
}

async function getSessionDetail(name) {
  const trimmed = (name || "").trim();
  if (!trimmed) throw new Error("Session name required");
  const fk = await getCurrentSessionFolderKey();
  const sessions = await getSessionsMapForFolder(fk);
  const raw = sessions[trimmed];
  if (!raw) throw new Error("Session not found");
  return { name: trimmed, snapshot: normalizeSessionSnapshot(raw) };
}

async function saveSessionData(name, snapshot) {
  const trimmed = (name || "").trim();
  if (!trimmed) throw new Error("Session name required");
  const snap = touchSessionMeta(normalizeSessionSnapshot(snapshot));
  if (!snap.windows.length) throw new Error("Session needs at least one window");
  const fk = await getCurrentSessionFolderKey();
  const sessions = await getSessionsMapForFolder(fk);
  sessions[trimmed] = snap;
  try {
    await setSessionsMapForFolder(fk, sessions);
  } catch (e) {
    if (e && e.message && String(e.message).toLowerCase().includes("quota")) {
      logError("sync quota exceeded saving session data", e);
    }
    throw e;
  }
  log("session data saved", trimmed);
}

async function deleteSession(name) {
  const trimmed = (name || "").trim();
  const fk = await getCurrentSessionFolderKey();
  const sessions = await getSessionsMapForFolder(fk);
  delete sessions[trimmed];
  await setSessionsMapForFolder(fk, sessions);
  const pend = await getPendingRestore();
  if (pend === trimmed) await clearPendingRestore();
  log("session deleted", trimmed);
}

async function getStateForPopup() {
  try {
    const scripts = await getStoredScripts();
    const sourceUrl = await getScriptSourceUrl();
    const extra = await getExtraUrls();
    const { folders, currentKey } = await getSessionFoldersState();
    const sessObj =
      folders[currentKey] &&
      folders[currentKey].sessions &&
      typeof folders[currentKey].sessions === "object" &&
      !Array.isArray(folders[currentKey].sessions)
        ? folders[currentKey].sessions
        : {};
    const sessionNames = Object.keys(sessObj).sort();
    const folderList = Object.keys(folders).sort();
    const folderGithubRel = {};
    for (const k of folderList) {
      folderGithubRel[k] = (folders[k] && folders[k].githubRelativePath) || "";
    }
    const last = await chrome.storage.local.get(STORAGE.LAST_FETCH);
    const pendingRestore = await getPendingRestore();
    let extensionVersion = "";
    try {
      extensionVersion = chrome.runtime.getManifest().version || "";
    } catch (e) {
      extensionVersion = "";
    }
    const hasHostAccess = await hasOptionalHostAccess();
    const setupData = await chrome.storage.local.get(STORAGE.SETUP_DISMISSED);
    const setupDismissed = !!setupData[STORAGE.SETUP_DISMISSED];
    const pendingData = await chrome.storage.local.get([
      STORAGE.PENDING_FIRST_POPUP_REFRESH,
      STORAGE.PENDING_INITIAL_SESSION_PULL,
    ]);
    const pendingFirstPopupRefresh = !!pendingData[STORAGE.PENDING_FIRST_POPUP_REFRESH];
    const pendingInitialSessionPull = !!pendingData[STORAGE.PENDING_INITIAL_SESSION_PULL];
    const gh = await getGithubSettings();
    const ghPathForFolder = await getGithubPathForFolder(currentKey);
    const ghErr = await chrome.storage.local.get(STORAGE.GITHUB_SYNC_LAST_ERROR);
    const ghOk = await chrome.storage.local.get(STORAGE.GITHUB_SYNC_LAST_OK);
    return {
      scripts,
      scriptSourceUrl: sourceUrl,
      extraScriptUrls: extra.join("\n"),
      sessions: sessionNames,
      currentSessionFolder: currentKey,
      sessionFolders: folderList,
      folderGithubRelativePaths: folderGithubRel,
      lastScriptFetch: last[STORAGE.LAST_FETCH] || null,
      pendingRestoreSession: pendingRestore,
      loginUrls: LOGIN_WINDOW_URLS,
      extensionVersion,
      hasHostAccess,
      setupDismissed,
    pendingFirstPopupRefresh,
    pendingInitialSessionPull,
    githubOwner: gh.owner,
      githubRepo: gh.repo,
      githubBranch: gh.branch,
      githubPath: gh.path,
      githubSessionsRoot: gh.sessionsRoot || "",
      githubEffectiveSessionFilePath: ghPathForFolder.path,
      githubTokenConfigured: !!gh.token,
      githubBakedIn: !!String(
        (self.BAKED_GITHUB_DEFAULTS && self.BAKED_GITHUB_DEFAULTS.token) || ""
      ).trim(),
      githubSyncLastOk: ghOk[STORAGE.GITHUB_SYNC_LAST_OK] || null,
      githubSyncLastError: ghErr[STORAGE.GITHUB_SYNC_LAST_ERROR] || "",
      stateLoadError: "",
    };
  } catch (e) {
    logError("getStateForPopup failed — returning safe empty state", e);
    let extensionVersion = "";
    try {
      extensionVersion = chrome.runtime.getManifest().version || "";
    } catch (e2) {
      extensionVersion = "";
    }
    return {
      scripts: [],
      scriptSourceUrl: DEFAULT_SCRIPT_SOURCE_URL,
      extraScriptUrls: "",
      sessions: [],
      currentSessionFolder: DEFAULT_SESSION_FOLDER,
      sessionFolders: [DEFAULT_SESSION_FOLDER],
      folderGithubRelativePaths: { [DEFAULT_SESSION_FOLDER]: "" },
      lastScriptFetch: null,
      pendingRestoreSession: null,
      loginUrls: LOGIN_WINDOW_URLS,
      extensionVersion,
      hasHostAccess: false,
      setupDismissed: false,
      pendingFirstPopupRefresh: false,
      pendingInitialSessionPull: false,
      githubOwner: "",
      githubRepo: "",
      githubBranch: "main",
      githubPath: "sessions/donkeycode-sessions.json",
      githubSessionsRoot: "sessions",
      githubEffectiveSessionFilePath: "sessions/donkeycode-sessions.json",
      githubTokenConfigured: false,
      githubBakedIn: false,
      githubSyncLastOk: null,
      githubSyncLastError: "",
      stateLoadError: String(e && e.message ? e.message : e),
    };
  }
}

chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => {
  (async () => {
    try {
      switch (message?.type) {
        case "GET_STATE": {
          const state = await getStateForPopup();
          sendResponse({ ok: true, ...state });
          break;
        }
        case "REQUEST_HOST_ACCESS": {
          const granted = await new Promise((resolve) => {
            try {
              chrome.permissions.request(
                { origins: OPTIONAL_ORIGIN_PATTERNS },
                resolve
              );
            } catch (e) {
              logError("permissions.request failed", e);
              resolve(false);
            }
          });
          if (granted) await ensureHostAccessAndBridge();
          else await unregisterBridgeContentScripts();
          const hasHostAccess = await hasOptionalHostAccess();
          await updateInstallBadge();
          sendResponse({ ok: true, granted, hasHostAccess });
          break;
        }
        case "DISMISS_SETUP_BANNER": {
          await chrome.storage.local.set({ [STORAGE.SETUP_DISMISSED]: true });
          await updateInstallBadge();
          sendResponse({ ok: true });
          break;
        }
        case "OPEN_WELCOME_TAB": {
          const url = chrome.runtime.getURL("welcome.html");
          await chrome.tabs.create({ url });
          sendResponse({ ok: true });
          break;
        }
        case "POPUP_CONSUMED_FIRST_REFRESH": {
          await chrome.storage.local.remove(STORAGE.PENDING_FIRST_POPUP_REFRESH);
          sendResponse({ ok: true });
          break;
        }
        case "CONSUMED_INITIAL_SESSION_PULL": {
          await chrome.storage.local.remove(STORAGE.PENDING_INITIAL_SESSION_PULL);
          sendResponse({ ok: true });
          break;
        }
        /**
         * Welcome page step 3: set first-run refresh flag and open the action popup from
         * the service worker while handling sendMessage (often works when openPopup from
         * welcome.html does not).
         */
        case "OPEN_POPUP_AFTER_WELCOME": {
          await chrome.storage.local.set({
            [STORAGE.PENDING_FIRST_POPUP_REFRESH]: true,
          });
          let opened = false;
          try {
            if (chrome.action && typeof chrome.action.openPopup === "function") {
              await chrome.action.openPopup();
              opened = true;
            }
          } catch (e) {
            logWarn("OPEN_POPUP_AFTER_WELCOME openPopup failed", e);
          }
          sendResponse({ ok: true, opened });
          break;
        }
        case "OPEN_EXTENSIONS_PAGE_FOR_PIN": {
          const id = chrome.runtime.id;
          const scheme =
            typeof navigator !== "undefined" &&
            /Edg\//.test(navigator.userAgent || "")
              ? "edge://"
              : "chrome://";
          const url = scheme + "extensions/?id=" + encodeURIComponent(id);
          await chrome.tabs.create({ url });
          sendResponse({ ok: true });
          break;
        }
        case "SET_GITHUB_SYNC_SETTINGS": {
          const payload = message.payload || {};
          const rootInput =
            (payload.sessionsRoot || payload.path || "sessions").trim() || "sessions";
          const sessionsRoot = normalizeUserSessionsRootInput(rootInput);
          const legacyDisplayPath = defaultSessionFilePathForRoot(sessionsRoot);
          const patch = {
            [STORAGE.GITHUB_OWNER]: (payload.owner || "").trim(),
            [STORAGE.GITHUB_REPO]: (payload.repo || "").trim(),
            [STORAGE.GITHUB_BRANCH]: (payload.branch || "main").trim() || "main",
            [STORAGE.GITHUB_SESSIONS_ROOT]: sessionsRoot,
            [STORAGE.GITHUB_PATH]: legacyDisplayPath,
          };
          const tok = (payload.token || "").trim();
          if (tok) patch[STORAGE.GITHUB_PAT] = tok;
          await chrome.storage.local.set(patch);
          log("GitHub sync settings saved", "sessions root", sessionsRoot);
          sendResponse({ ok: true });
          break;
        }
        case "REMOVE_GITHUB_TOKEN": {
          await chrome.storage.local.remove(STORAGE.GITHUB_PAT);
          log("GitHub token removed");
          sendResponse({ ok: true });
          break;
        }
        case "GITHUB_SESSIONS_PULL": {
          try {
            const result = await githubSyncPull();
            sendResponse({
              ok: true,
              sessions: result.sessions,
              pullErrors: result.pullErrors || [],
              discoveredRemoteFolders: result.discoveredRemoteFolders || [],
              newLocalFolders: result.newLocalFolders || [],
            });
          } catch (e) {
            await chrome.storage.local.set({
              [STORAGE.GITHUB_SYNC_LAST_ERROR]: String(
                e && e.message ? e.message : e
              ),
            });
            sendResponse({
              ok: false,
              error: String(e && e.message ? e.message : e),
            });
          }
          break;
        }
        case "GITHUB_SESSIONS_PUSH": {
          try {
            const result = await githubSyncPush();
            sendResponse({
              ok: true,
              sessions: result.sessions,
            });
          } catch (e) {
            await chrome.storage.local.set({
              [STORAGE.GITHUB_SYNC_LAST_ERROR]: String(
                e && e.message ? e.message : e
              ),
            });
            sendResponse({
              ok: false,
              error: String(e && e.message ? e.message : e),
            });
          }
          break;
        }
        case "GITHUB_SESSIONS_PUSH_ALL": {
          try {
            const result = await githubSyncPushAll();
            sendResponse({
              ok: true,
              sessions: result.sessions,
              pushErrors: result.pushErrors || [],
            });
          } catch (e) {
            await chrome.storage.local.set({
              [STORAGE.GITHUB_SYNC_LAST_ERROR]: String(
                e && e.message ? e.message : e
              ),
            });
            sendResponse({
              ok: false,
              error: String(e && e.message ? e.message : e),
            });
          }
          break;
        }
        case "GITHUB_SESSIONS_SYNC_ALL": {
          try {
            const result = await githubSyncAll();
            sendResponse({
              ok: true,
              sessions: result.sessions,
              pullErrors: result.pullErrors || [],
              pushErrors: result.pushErrors || [],
              discoveredRemoteFolders: result.discoveredRemoteFolders || [],
              newLocalFolders: result.newLocalFolders || [],
            });
          } catch (e) {
            await chrome.storage.local.set({
              [STORAGE.GITHUB_SYNC_LAST_ERROR]: String(
                e && e.message ? e.message : e
              ),
            });
            sendResponse({
              ok: false,
              error: String(e && e.message ? e.message : e),
            });
          }
          break;
        }
        case "REFRESH_SCRIPTS": {
          log("refresh scripts requested");
          const scripts = await loadScriptsFromRemote();
          await resyncAllTabs();
          sendResponse({ ok: true, scripts });
          break;
        }
        case "SET_SCRIPT_ENABLED": {
          await toggleScript(message.scriptId, !!message.enabled);
          const scripts = await getStoredScripts();
          sendResponse({ ok: true, scripts });
          break;
        }
        case "SET_SCRIPT_SOURCE_URL": {
          const url = (message.url || "").trim();
          if (!url) throw new Error("URL required");
          await chrome.storage.sync.set({ [STORAGE.SCRIPT_SOURCE]: url });
          log("script source URL updated");
          const scripts = await loadScriptsFromRemote();
          await resyncAllTabs();
          sendResponse({ ok: true, scripts });
          break;
        }
        case "SET_EXTRA_SCRIPT_URLS": {
          const text = message.text || "";
          const lines = text
            .split(/\r?\n/)
            .map((l) => l.trim())
            .filter(Boolean);
          await chrome.storage.sync.set({ [STORAGE.EXTRA_URLS]: lines });
          log("extra URLs updated", lines.length);
          const scripts = await loadScriptsFromRemote();
          await resyncAllTabs();
          sendResponse({ ok: true, scripts });
          break;
        }
        case "PREVIEW_SESSION_CAPTURE": {
          const snap = await captureSessionSnapshot();
          const ordered = sortWindowsForRestore(snap.windows);
          const worksheetIndices = [];
          for (let i = 0; i < snap.windows.length; i++) {
            if (worksheetPrimaryUrlForWindow(snap.windows[i])) {
              worksheetIndices.push(i);
            }
          }
          const orderSet = new Set(worksheetIndices);
          const worksheetIndicesOrdered = [];
          for (const w of ordered) {
            const idx = snap.windows.indexOf(w);
            if (idx >= 0 && orderSet.has(idx)) {
              worksheetIndicesOrdered.push(idx);
            }
          }
          sendResponse({
            ok: true,
            snapshot: snap,
            worksheetWindowIndices: worksheetIndicesOrdered,
          });
          break;
        }
        case "SAVE_SESSION": {
          await saveSession(message.name, message.snapshot);
          const fk = await getCurrentSessionFolderKey();
          const sessions = Object.keys(await getSessionsMapForFolder(fk)).sort();
          const githubAutoSync = await maybeAutoPushSessionsToGithub();
          sendResponse({ ok: true, sessions, githubAutoSync });
          break;
        }
        case "RESTORE_SESSION": {
          await restoreSession(message.name);
          sendResponse({ ok: true });
          break;
        }
        case "RESTORE_SESSION_AFTER_LOGIN": {
          await openLoginWindowsThenQueueRestore(message.name);
          const pending = await getPendingRestore();
          sendResponse({ ok: true, pendingRestoreSession: pending });
          break;
        }
        case "COMPLETE_PENDING_RESTORE": {
          await completePendingRestore();
          sendResponse({ ok: true, pendingRestoreSession: null });
          break;
        }
        case "CANCEL_PENDING_RESTORE": {
          await clearPendingRestore();
          sendResponse({ ok: true, pendingRestoreSession: null });
          break;
        }
        case "GET_SESSION_DETAIL": {
          const detail = await getSessionDetail(message.name);
          sendResponse({ ok: true, ...detail });
          break;
        }
        case "SAVE_SESSION_DATA": {
          await saveSessionData(message.name, message.snapshot);
          const fk = await getCurrentSessionFolderKey();
          const sessions = Object.keys(await getSessionsMapForFolder(fk)).sort();
          const githubAutoSync = await maybeAutoPushSessionsToGithub();
          sendResponse({ ok: true, sessions, githubAutoSync });
          break;
        }
        case "DELETE_SESSION": {
          await deleteSession(message.name);
          const fk = await getCurrentSessionFolderKey();
          const sessions = Object.keys(await getSessionsMapForFolder(fk)).sort();
          const githubAutoSync = await maybeAutoPushSessionsToGithub();
          sendResponse({ ok: true, sessions, githubAutoSync });
          break;
        }
        case "SET_CURRENT_SESSION_FOLDER": {
          const key = normalizeFolderKey(message.folderKey);
          await getSessionFoldersState();
          const d = await chrome.storage.local.get(STORAGE.SESSION_FOLDERS_V2);
          let folders = d[STORAGE.SESSION_FOLDERS_V2] || {};
          if (!folders[key]) folders[key] = { sessions: {} };
          await chrome.storage.local.set({
            [STORAGE.CURRENT_SESSION_FOLDER]: key,
            [STORAGE.SESSION_FOLDERS_V2]: folders,
          });
          const st = await getStateForPopup();
          sendResponse({ ok: true, ...st });
          break;
        }
        case "ADD_SESSION_FOLDER": {
          const key = normalizeFolderKey(message.folderKey);
          if (key === DEFAULT_SESSION_FOLDER) throw new Error("Use a non-default folder name");
          const { folders } = await getSessionFoldersState();
          if (folders[key]) throw new Error("Folder already exists");
          folders[key] = {
            sessions: {},
            githubRelativePath: (message.githubRelativePath || "").trim(),
          };
          await chrome.storage.local.set({
            [STORAGE.SESSION_FOLDERS_V2]: folders,
            [STORAGE.CURRENT_SESSION_FOLDER]: key,
          });
          let githubPlaceholder = null;
          try {
            githubPlaceholder = await ensureGithubSessionsPlaceholderForFolder(key);
          } catch (e) {
            logWarn("GitHub placeholder create failed for new folder", key, e);
            githubPlaceholder = {
              skipped: false,
              error: String(e && e.message ? e.message : e),
            };
          }
          const st = await getStateForPopup();
          sendResponse({ ok: true, ...st, githubPlaceholder });
          break;
        }
        case "DELETE_SESSION_FOLDER": {
          const key = normalizeFolderKey(message.folderKey);
          if (key === DEFAULT_SESSION_FOLDER) throw new Error("Cannot delete the default folder");
          const { folders, currentKey } = await getSessionFoldersState();
          if (!folders[key]) throw new Error("Unknown folder");
          const deleteRemote = !!message.deleteRemote;
          let remoteDeleted = false;
          let remoteError = "";
          if (deleteRemote) {
            const gh = await getGithubSettings();
            if (!gh.token || !gh.owner || !gh.repo) {
              throw new Error("Configure GitHub owner, repo, and token to delete remote file.");
            }
            try {
              const settings = await getGithubPathForFolder(key);
              const file = await fetchGithubSessionsFile(settings);
              if (file && file.sha) {
                await githubDeleteRepoFile(settings, file.sha);
                remoteDeleted = true;
                log("GitHub: deleted remote sessions file for folder", key, settings.path);
              }
            } catch (e) {
              remoteError = String(e && e.message ? e.message : e);
              logWarn("GitHub remote delete failed for folder", key, e);
            }
            if (remoteError) {
              throw new Error("Could not delete file on GitHub: " + remoteError);
            }
          }
          delete folders[key];
          let nextCur = currentKey;
          if (currentKey === key) {
            nextCur = DEFAULT_SESSION_FOLDER;
          }
          await chrome.storage.local.set({
            [STORAGE.SESSION_FOLDERS_V2]: folders,
            [STORAGE.CURRENT_SESSION_FOLDER]: nextCur,
          });
          const st = await getStateForPopup();
          sendResponse({
            ok: true,
            ...st,
            remoteDeleted,
            remoteError: remoteError || undefined,
          });
          break;
        }
        case "SET_SESSION_FOLDER_GITHUB_PATH": {
          const key = normalizeFolderKey(message.folderKey);
          const { folders } = await getSessionFoldersState();
          if (!folders[key]) throw new Error("Unknown folder");
          folders[key].githubRelativePath = (message.githubRelativePath || "").trim();
          await chrome.storage.local.set({ [STORAGE.SESSION_FOLDERS_V2]: folders });
          const st = await getStateForPopup();
          sendResponse({ ok: true, ...st });
          break;
        }
        case "GET_SESSION_FOLDERS_TREE": {
          const { folders, currentKey } = await getSessionFoldersState();
          const tree = {};
          for (const k of Object.keys(folders)) {
            const s = (folders[k] && folders[k].sessions) || {};
            tree[k] = {
              githubRelativePath: (folders[k] && folders[k].githubRelativePath) || "",
              sessionNames: Object.keys(s).sort(),
              sessionCount: Object.keys(s).length,
            };
          }
          const gh = await getGithubSettings();
          sendResponse({
            ok: true,
            tree,
            currentFolder: currentKey,
            githubBasePath: gh.sessionsRoot || "",
            githubDefaultFilePath: gh.path,
          });
          break;
        }
        case "GITHUB_LIST_REPO_CONTENTS": {
          const prefix = ((message.pathPrefix || "") + "").trim().replace(/^\/+/, "");
          const settings = await getGithubSettings();
          if (!settings.token || !settings.owner || !settings.repo) {
            throw new Error("Configure GitHub in Settings first.");
          }
          const contentsPath = prefix
            ? "/contents/" +
              prefix.split("/").map((p) => encodeURIComponent(p)).join("/")
            : "/contents";
          const apiPath =
            "/repos/" +
            encodeURIComponent(settings.owner) +
            "/" +
            encodeURIComponent(settings.repo) +
            contentsPath +
            "?ref=" +
            encodeURIComponent(settings.branch);
          const json = await githubApiRequest(apiPath, { method: "GET" }, settings.token);
          const items = Array.isArray(json) ? json : [];
          sendResponse({
            ok: true,
            path: prefix,
            items: items.map((it) => ({
              name: it.name,
              path: it.path,
              type: it.type,
            })),
          });
          break;
        }
        case "OPEN_SETTINGS_TAB": {
          const url = chrome.runtime.getURL("settings.html");
          await chrome.tabs.create({ url });
          sendResponse({ ok: true });
          break;
        }
        case "GM_XHR": {
          const scriptId = message.scriptId;
          const details = message.details || {};
          const reqUrl = details.url;
          const method = (details.method || "GET").toUpperCase();

          if (!scriptId || !reqUrl) {
            sendResponse({ error: "scriptId and url required" });
            break;
          }

          const scripts = await getStoredScripts();
          const script = scripts.find((s) => s.id === scriptId);
          if (!script) {
            logWarn("GM_XHR: unknown script", scriptId);
            sendResponse({ error: "Unknown script" });
            break;
          }

          const connects = script.connects || [];
          if (!urlAllowedByConnects(reqUrl, connects)) {
            logWarn("GM_XHR blocked by @connect", reqUrl, connects);
            sendResponse({ error: "URL not allowed by script @connect" });
            break;
          }

          if (!(await hasOriginAccessForUrl(reqUrl))) {
            logWarn("GM_XHR blocked (no host permission)", reqUrl);
            sendResponse({
              error: "Host permission not granted for this URL. Open DonkeyCode settings and allow website access.",
            });
            break;
          }

          log("GM_xmlhttpRequest", method, reqUrl, script.name);
          try {
            const init = { method, redirect: "follow" };
            if (details.headers && typeof details.headers === "object") {
              const h = new Headers();
              for (const k of Object.keys(details.headers)) {
                h.append(k, details.headers[k]);
              }
              init.headers = h;
            }
            const res = await fetch(reqUrl, init);
            const text = await res.text();
            log("GM_xmlhttpRequest done", res.status, reqUrl);
            sendResponse({
              responseText: text,
              status: res.status,
              statusText: res.statusText,
              finalUrl: res.url,
            });
          } catch (e) {
            logError("GM_xmlhttpRequest fetch failed", reqUrl, e);
            sendResponse({
              error: String(e && e.message ? e.message : e),
            });
          }
          break;
        }
        default:
          sendResponse({ ok: false, error: "Unknown message type" });
      }
    } catch (e) {
      logError("message handler error", e);
      sendResponse({ ok: false, error: String(e && e.message ? e.message : e) });
    }
  })();
  return true;
});

// Initial load
ensureDailyAlarm();
ensureHostAccessAndBridge().catch((e) => logError("initial host/bridge", e));
loadScriptsFromRemote()
  .then(() => updateInstallBadge())
  .catch((e) => {
    logError("initial load failed", e);
    updateInstallBadge();
  });
